### ISSUE TITLE
Where is the cipher.h ?

### ISSUE THREAD

**Issue by hariskoko** [openluopworld/rectangle#1]
Where I can find the cipher.h ??

**Comment by openluopworld** [comment]
Hello, this code is based on [FELICS](https://www.cryptolux.org/index.php/FELICS). You can download it from that page, then you will see _cipher.h_ is under _/FELICS/block_ciphers/source/common/_.
Wishes.

**Comment by hariskoko** [comment]
thanks.. I got it

**Comment by hariskoko** [comment]
is it on C programming ?

**Comment by openluopworld** [comment]
Yeah, some versions are assembly code. I will consider to add a pure c implementation in a few days.

If you just want the c implementation, you can get it from RECTANGLE_64_128_v04 with the following steps.

* In  rectangle.h

a) define rounds
`#define NUMBER_OF_ROUNDS 25`

b) define the interfaces
```
void encrypt(uint8_t *block, uint8_t *roundKeys);
void decrypt(uint8_t *block, uint8_t *roundKeys);
void keySchedule_128(uint8_t *key, uint8_t *roundKeys);
void keySchedule_80(uint8_t *key, uint8_t *roundKeys);
```

* In rectangle.c

a) Add the round keys
```
static const uint8_t RC[25] = {
	0x01, 0x02, 0x04, 0x09, 0x12, 0x05, 0x0b, 0x16, 
	0x0c, 0x19, 0x13, 0x07, 0x0f, 0x1f, 0x1e, 0x1c, 
	0x18, 0x11, 0x03, 0x06, 0x0d, 0x1b, 0x17, 0x0e, 0x1d};
```
b) Get encrypt from _/RECTANGLE_64_128_v04/encrypt.c_. The structure of the file is
```
#ifdef AVR
// avr code here
#else
#ifdef MSP
// msp code here
#else
// and here is the code you need
#endif
#endif
```
c) The other three functions can be got from _/RECTANGLE_64_128_v04/decrypt.c_, 
_/RECTANGLE_64_128_v04/encryption_key_schedule.c_ and _/RECTANGLE_64_80_v04/encryption_key_schedule.c_. The structures are all the same. Since RECTANGLE has two versions of key size, two different key schedule functions are needed. Attention that, **READ_ROUND_KEY_DOUBLE_WORD, READ_ROUND_KEY_WORD, and READ_Z_BYTE should be deleted from the functions.**

Or you can have your own implementation. The cipher is described in details in the paper[1].

[1] https://eprint.iacr.org/2014/084.pdf

Best wishes.

**Comment by openluopworld** [comment]
I have added the C implementation. It is under directory _RECTANGLE_reference_. Wishes.

**Comment by hariskoko** [comment]
thank you so much.. :)
